#pragma once

#define BoneNum 33
#define Bone_neck 0
#define Bone_spine3 1
#define Bone_spine2 2
#define Bone_spine1 3
#define Bone_spine 4
#define Bone_waist 5
#define Bone_pelvis 6
#define Bone_collarboneR 7
#define Bone_shoulderR 8
#define Bone_upperArmR 9
#define Bone_upperArm1R 10
#define Bone_lowerArmR 11
#define Bone_lowerArm1R 12
#define Bone_lowerArm2R 13
#define Bone_collarboneL 14
#define Bone_shoulderL 15
#define Bone_upperArmL 16
#define Bone_upperArm1L 17
#define Bone_lowerArmL 18
#define Bone_lowerArm1L 19
#define Bone_lowerArm2L 20
#define Bone_pelvisR 21
#define Bone_hipR 22
#define Bone_upperLegR 23
#define Bone_upperLeg1R 24
#define Bone_lowerLegR 25
#define Bone_pelvisL 26
#define Bone_hipL 27
#define Bone_upperLegL 28
#define Bone_upperLeg1L 29
#define Bone_lowerLegL 30
#define Bone_ribR 31
#define Bone_ribL 32
