#pragma once

#define WeightNum 16
#define JointNum 16
#define Joint_neck 0
#define Joint_shoulderMid 1
#define Joint_shoulderR 2
#define Joint_elbowR 3
#define Joint_wristR 4
#define Joint_waist 5
#define Joint_pelvisMid 6
#define Joint_pelvisR 7
#define Joint_kneeR 8
#define Joint_ankleR 9
#define Joint_pelvisL 10
#define Joint_kneeL 11
#define Joint_ankleL 12
#define Joint_shoulderL 13
#define Joint_elbowL 14
#define Joint_wristL 15

#define ExpandedJointNum 34
#define Joint_spine 16
#define Joint_spine1 17
#define Joint_spine2 18
#define Joint_spine3 19
#define Joint_ribR 20
#define Joint_collarboneR 21
#define Joint_shoulderTwistR 22
#define Joint_elbowTwistR 23
#define Joint_elbowTwist1R 24
#define Joint_ribL 25
#define Joint_collarboneL 26
#define Joint_shoulderTwistL 27
#define Joint_elbowTwistL 28
#define Joint_elbowTwist1L 29
#define Joint_hipR 30
#define Joint_hipTwistR 31
#define Joint_hipL 32
#define Joint_hipTwistL 33
